import { ApiProperty } from '@nestjs/swagger';
import { IsInt, Min } from 'class-validator';

export class InitializePaymentRequestDto {
  @ApiProperty({
    example: 5000,
    description: 'Amount in Kobo (₦50.00 → 5000). Must be at least 1 Kobo.',
  })
  @IsInt()
  @Min(1)
  amount: number;
}

export class InitializePaymentResponse {
  @ApiProperty({
    example: 'p7z0q9p2x1',
    description: 'Unique reference generated by Paystack',
  })
  reference: string;

  @ApiProperty({
    example: 'https://checkout.paystack.com/abcdef12345',
    description: 'URL where the user should complete payment',
  })
  authorization_url: string;
}

export class InitializePaymentResponseDto {
  @ApiProperty({ type: InitializePaymentResponse })
  data: InitializePaymentResponse;
}
